#########################################################################################
# Use the `queries` block to change the default display of query results.               #
#########################################################################################

queries:
  # Ignore warning: This replaces only the first occurrence of ''
  - exclude: js/incomplete-sanitization